FROM python:3.8

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy your Jupyter notebook(s) into the container
COPY Generalreview.ipynb  .

# Expose the port Voilà will use
EXPOSE 8866

# Command to run Voilà
CMD ["voila", "Generalreview.ipynb", "--port=8866", "--no-browser"]